/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package document_finder_service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the DocumentInfo service. Represents a row in the &quot;FOO_DocumentInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link document_finder_service.model.impl.DocumentInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link document_finder_service.model.impl.DocumentInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DocumentInfo
 * @see document_finder_service.model.impl.DocumentInfoImpl
 * @see document_finder_service.model.impl.DocumentInfoModelImpl
 * @generated
 */
@ProviderType
public interface DocumentInfoModel extends BaseModel<DocumentInfo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document info model instance should use the {@link DocumentInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this document info.
	 *
	 * @return the primary key of this document info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document info.
	 *
	 * @param primaryKey the primary key of this document info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the doc ID of this document info.
	 *
	 * @return the doc ID of this document info
	 */
	public long getDocID();

	/**
	 * Sets the doc ID of this document info.
	 *
	 * @param DocID the doc ID of this document info
	 */
	public void setDocID(long DocID);

	/**
	 * Returns the doc name of this document info.
	 *
	 * @return the doc name of this document info
	 */
	@AutoEscape
	public String getDocName();

	/**
	 * Sets the doc name of this document info.
	 *
	 * @param DocName the doc name of this document info
	 */
	public void setDocName(String DocName);

	/**
	 * Returns the doc gen of this document info.
	 *
	 * @return the doc gen of this document info
	 */
	@AutoEscape
	public String getDocGen();

	/**
	 * Sets the doc gen of this document info.
	 *
	 * @param DocGen the doc gen of this document info
	 */
	public void setDocGen(String DocGen);

	/**
	 * Returns the doc fee of this document info.
	 *
	 * @return the doc fee of this document info
	 */
	public int getDocFee();

	/**
	 * Sets the doc fee of this document info.
	 *
	 * @param DocFee the doc fee of this document info
	 */
	public void setDocFee(int DocFee);

	/**
	 * Returns the doc size of this document info.
	 *
	 * @return the doc size of this document info
	 */
	@AutoEscape
	public String getDocSize();

	/**
	 * Sets the doc size of this document info.
	 *
	 * @param DocSize the doc size of this document info
	 */
	public void setDocSize(String DocSize);

	/**
	 * Returns the doc pre url of this document info.
	 *
	 * @return the doc pre url of this document info
	 */
	@AutoEscape
	public String getDocPreUrl();

	/**
	 * Sets the doc pre url of this document info.
	 *
	 * @param DocPreUrl the doc pre url of this document info
	 */
	public void setDocPreUrl(String DocPreUrl);

	/**
	 * Returns the doc down url of this document info.
	 *
	 * @return the doc down url of this document info
	 */
	@AutoEscape
	public String getDocDownUrl();

	/**
	 * Sets the doc down url of this document info.
	 *
	 * @param DocDownUrl the doc down url of this document info
	 */
	public void setDocDownUrl(String DocDownUrl);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		document_finder_service.model.DocumentInfo documentInfo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<document_finder_service.model.DocumentInfo> toCacheModel();

	@Override
	public document_finder_service.model.DocumentInfo toEscapedModel();

	@Override
	public document_finder_service.model.DocumentInfo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}